// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pxrbsjdrcYiKeJrrydSqC9
// Component: I5Q14DJIrh8zkA
import * as React from "react";
import { Link } from "gatsby";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: DYJN_6hRhobBcR/component
import ProductCard from "../../ProductCard"; // plasmic-import: m9xraW-kpySFIb/component
import Ratings from "../../Ratings"; // plasmic-import: hkLb2r8c9IygmP/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: NbzX9R2oE7Tr_C/component
import BlogPost from "../../BlogPost"; // plasmic-import: d4PABHe6TTTeYg/component
import Footer from "../../Footer"; // plasmic-import: t1MJfdGbdT9xN/component
import { useScreenVariants as useScreenVariantszNo6Oijq3JlNiY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZNo6oijq3JlNiY/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_tekkou_studios.module.css"; // plasmic-import: pxrbsjdrcYiKeJrrydSqC9/projectcss
import * as sty from "./PlasmicAboutUs.module.css"; // plasmic-import: I5Q14DJIrh8zkA/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 0VwAWSlI1cyKAc/icon
import galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: u3z8jgzcZrmHl-/picture
import igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5 from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: YEIKuc4Us-uOc5/picture
import scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: F1Dc1rqcLUfMdJ/picture
import freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: QR2sCt8irZr_xZ/picture
import f2B5KNe2NkQlu4Yi from "./images/f2.jpg"; // plasmic-import: b5kNE2nkQLU4YI/picture
import f3Z1Tdfnxb3V4H5T from "./images/f3.jpg"; // plasmic-import: Z1Tdfnxb3V4h5T/picture
import f4UpCxJZtQkBmwy from "./images/f4.jpg"; // plasmic-import: UpCxJ-ZtQKBmwy/picture
import b1E3AdVKnEdWhdSk from "./images/b1.jpg"; // plasmic-import: e3adVKnEdWhdSK/picture
import b2U3LpTcnWSQ4N from "./images/b2.jpg"; // plasmic-import: u3LpTcnW-sQ4_N/picture
import b3JjuBmEbCNjmCwe from "./images/b3.jpg"; // plasmic-import: jjuBMEbCNjmCwe/picture
import adidasWP3E6VBobZgXt from "./images/adidas.png"; // plasmic-import: wP3e6VBobZg_XT/picture
import hmIbgwVFs1NGuwJb from "./images/hm.png"; // plasmic-import: ibgwVFs1nGuwJB/picture
import kappaB70FlI1Ij5EeDw from "./images/kappa.png"; // plasmic-import: b70FlI1Ij5eeDw/picture
import lacosteQq5M0ROc1FK9Zv from "./images/lacoste.png"; // plasmic-import: QQ5m0rOc1fK9zv/picture
import levisBtwPEu6Om5E0Cj from "./images/levis.png"; // plasmic-import: btwPEu6Om5E0cj/picture
import plant6JpgWypOSqMwkLljC from "./images/plant6Jpg.png"; // plasmic-import: Wyp-oSqMWKLljC/picture
import plant1Jpg4WnEmY0KtT5T from "./images/plant1Jpg.png"; // plasmic-import: 4wnEmY0kt_T5-t/picture
import plant7JpgLppZ16Jixs6SM from "./images/plant7Jpg.png"; // plasmic-import: LppZ16jixs6s_m/picture
import plant5JpgY7RlFovmeoVvz from "./images/plant5Jpg.png"; // plasmic-import: Y7Rl-FovmeoVvz/picture
import plant41JpgDrXI302Mcggq from "./images/plant41Jpg.png"; // plasmic-import: drX__I302mcggq/picture
import plant31JpgY8QgmNoCoGRaU8 from "./images/plant31Jpg.png"; // plasmic-import: Y8qgmNoCoGRaU8/picture
import plant9WebpBuUZlDvLXdwOt from "./images/plant9Webp.webp"; // plasmic-import: BU_UZlDvLXdwOT/picture
import plant2WebpTwez09OFzcfPxW from "./images/plant2Webp.webp"; // plasmic-import: TWEZ09oFzcfPxW/picture
import nanTalkwebp5PFeRGfvIyqjo from "./images/nanTalkwebp.webp"; // plasmic-import: 5P_FeRGfvIYQJO/picture
import teamwebpJkVhXJc87CmYn from "./images/teamwebp.webp"; // plasmic-import: jkVhXJc87CmYn_/picture

createPlasmicElementProxy;

export const PlasmicAboutUs__VariantProps = new Array();

export const PlasmicAboutUs__ArgProps = new Array();

const $$ = {};

export function Head() {
  return <></>;
}

function PlasmicAboutUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszNo6Oijq3JlNiY()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__w23K1)}>
            <Header2
              className={classNames("__wab_instance", sty.header2__gKvQi)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__ll5Oa)}>
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ufFRn)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"We are Planty"}
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__db4Js)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bKxMm
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                        : "Well, not really. We\u2019re Snipcart \u2014a bunch of geeks from Qu\u00e9bec City. Planty is a theme we built for Stackbit , a killer JAMstack site-builder. To enable e-commerce on Planty, you\u2019ll need to sign up for Snipcart. Testing is forever free, no credit card required."}
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___5J3M3)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___8DVd1)}>
                <Header2
                  className={classNames("__wab_instance", sty.header2___6Rpni)}
                />
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox__eWEiq)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__hdIv1
                )}
              >
                {"Top Collections"}
              </h2>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__y7WG)}
            >
              <div className={classNames(projectcss.all, sty.column__fdx4F)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__uitr0
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__j6Y3E)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl,
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__wnAft
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__oLsf1)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__i7Ix6
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___1GSD)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5,
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___1G5Wc
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__wTnfb)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yHjSg
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gFmUr)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__k0Ik1
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___4LZsn)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aLoW
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__alNeM)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ,
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__owWm4
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
            </p.Stack>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__xEj4W)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uh0Xn
                )}
              >
                {"Featured Products"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__yijqC)}
            >
              <div className={classNames(projectcss.all, sty.column__mo4Z)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__thyaK
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xMjYu
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zI7Jr
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x6B5E
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__r8EWw)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vjv5H
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qez8K)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2B5KNe2NkQlu4Yi,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__xn8Az
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__e88K6)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gc0Kr
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tyz3Y)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3Z1Tdfnxb3V4H5T,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___2MSjj
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__uPsm2)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__y4Ph7
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__y3FeM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4UpCxJZtQkBmwy,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__yElUh
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox__sltRd)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__a4GVt
                )}
              >
                {"Latest Blog"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__eqFlK)}
            >
              <div className={classNames(projectcss.all, sty.column___8PJ2)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__cdKgt)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__e1U4R)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1E3AdVKnEdWhdSk,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__bxExx)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___6GIcF)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dicfx)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2U3LpTcnWSQ4N,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__zFofq)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__xjgQo)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qySjC)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b3JjuBmEbCNjmCwe,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__izeCd)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___4BTp)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidasWP3E6VBobZgXt,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__i7Fe5)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmIbgwVFs1NGuwJb,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___4Nlgj)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaB70FlI1Ij5EeDw,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__opSb)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteQq5M0ROc1FK9Zv,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__k27DD)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levisBtwPEu6Om5E0Cj,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>
            <Footer
              className={classNames("__wab_instance", sty.footer___5VjV)}
            />
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mz3R8)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__oxyt0
                )}
              >
                {"Big plants"}
              </h2>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__e6Y6F)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___2Wqni)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___0Yxet)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant6JpgWypOSqMwkLljC,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__dJFyG)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__uwZP)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fj682)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9Vw7
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Donec finibus"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qxpoo
                    )}
                  >
                    {"bigplants"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__gXrDn
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___368Ac)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__i3P7N)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant1Jpg4WnEmY0KtT5T,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__woSIx)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__qYYrU)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__udmUv)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___8UIzj
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Nulla suscipit"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nwsop
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___1X4Oh
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__bDwn9)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xqEtA)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant7JpgLppZ16Jixs6SM,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__kHVjd)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__gLsld)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6YjDs)}
                >
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__qfKqk
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Sed consectetur"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5V5Ux
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___3I9P1
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cIhp5)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant5JpgY7RlFovmeoVvz,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__nd0UP)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___6Tu4L)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__tqWt)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__f6Wgu
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Vestibulum eget"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zoPMk
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__uk7UU
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__it5Qy)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__n8K1C
                )}
              >
                {"Cactuses"}
              </h2>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__wrOw6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__mkMGe)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___8C7Qw)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant41JpgDrXI302Mcggq,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___6Yc2A)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__un67K)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dGp03)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__pC6Js
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Cras molestie"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__djmt8
                    )}
                  >
                    {"cactuses "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__hKxio
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__pF2Ix)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yrThu)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant31JpgY8QgmNoCoGRaU8,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___6K632)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__baTtx)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__cycx7)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fTftU
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Curabitur eu tempor"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1NIh0
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__wtNBy
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__ceetP)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__r9CgC)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant9WebpBuUZlDvLXdwOt,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__vyMjw)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__jw4PB)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ym2B3)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ixdUo
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Fusce sagittis"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ihil4
                    )}
                  >
                    {"Fusce sagittis"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__mAdF6
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___4XVeX)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fdVlB)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant2WebpTwez09OFzcfPxW,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__lPtU)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__xRDxd)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ukkGo)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__iIGp
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Integer porta"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xuB7V
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__nd4Wa
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <div
            data-plasmic-name={"weLove"}
            data-plasmic-override={overrides.weLove}
            className={classNames(projectcss.all, sty.weLove)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___8Kg3W)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__ha0P)}
              >
                <div className={classNames(projectcss.all, sty.column__u9Hrb)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2ItAq)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "400px"
                        : "500px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"500px"}
                    loading={"lazy"}
                    src={{
                      src: nanTalkwebp5PFeRGfvIyqjo,
                      fullWidth: 1000,
                      fullHeight: 1498,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__wXvMf)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___0BCtj
                    )}
                  >
                    {"Testimonials"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9OcEi
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                      : "Now THAT is true, but we love web development even more. We talk about it on our blog, like, a lot.  We often craft live demos and open source these bad boys on GitHub. Matter of fact, this Planty theme is open source too! If you spot any bugs, open an issue, and we\u2019ll fire our junior dev. Just kidding Michael, you\u2019re good."}
                  </div>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
          <div
            data-plasmic-name={"weThink"}
            data-plasmic-override={overrides.weThink}
            className={classNames(projectcss.all, sty.weThink)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___1JHnw)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___9EMHa)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__zoEk1)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__zgok1
                    )}
                  >
                    {"We think plants are the future"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ckjUz
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                      : "Word. But good code can  solve a lots of problems, too. New and old. That\u2019s why we help beginners get started with web development through free content and tools, like this theme. We also believe the JAMstack might be one solid pillar on which we build that future."}
                  </div>
                </p.Stack>
                <div className={classNames(projectcss.all, sty.column__ilZyR)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vGtKl)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "400px"
                        : "500px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "500px"
                        : "500px"
                    }
                    loading={"lazy"}
                    src={{
                      src: teamwebpJkVhXJc87CmYn,
                      fullWidth: 1368,
                      fullHeight: 2048,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </p.Stack>
            </div>
          </div>
          <Footer className={classNames("__wab_instance", sty.footer__wDgGd)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "h1",
    "header",
    "featureItem",
    "bigPlants",
    "cactuses",
    "weLove",
    "weThink"
  ],

  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  header: ["header", "featureItem"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  weLove: ["weLove"],
  weThink: ["weThink"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    header: makeNodeComponent("header"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    weLove: makeNodeComponent("weLove"),
    weThink: makeNodeComponent("weThink"),
    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
