// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pxrbsjdrcYiKeJrrydSqC9
// Component: U2xBTGhaBJVBc
import * as React from "react";
import { Link } from "gatsby";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import ProductCard from "../../ProductCard"; // plasmic-import: m9xraW-kpySFIb/component
import Ratings from "../../Ratings"; // plasmic-import: hkLb2r8c9IygmP/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: NbzX9R2oE7Tr_C/component
import BlogPost from "../../BlogPost"; // plasmic-import: d4PABHe6TTTeYg/component
import Footer from "../../Footer"; // plasmic-import: t1MJfdGbdT9xN/component
import { useScreenVariants as useScreenVariantszNo6Oijq3JlNiY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZNo6oijq3JlNiY/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_tekkou_studios.module.css"; // plasmic-import: pxrbsjdrcYiKeJrrydSqC9/projectcss
import * as sty from "./PlasmicTekkouStudios.module.css"; // plasmic-import: U2xBTGhaBJVBc/css
import vlcsnap2023110717H04M07S779PngJgWZxojzGDue from "./images/vlcsnap2023110717H04M07S779Png.png"; // plasmic-import: JgWZxojzGDue/picture
import vlcsnap2023110718H09M08S497PngSWuzSRjSeAjQ from "./images/vlcsnap2023110718H09M08S497Png.png"; // plasmic-import: SWuzSRjSEAjQ/picture
import tekkouLogoSeptember20234Png2MWgS6QoX0KP from "./images/tekkouLogoSeptember20234Png.png"; // plasmic-import: 2mWgS6qoX0kP/picture
import sugarcreekLogoFullpngDBkCf3AHj from "./images/sugarcreekLogoFullpng.png"; // plasmic-import: DBkCf3AHj/picture
import vlcsnap2023052317H36M59S219PngMElD3RVyO from "./images/vlcsnap2023052317H36M59S219Png.png"; // plasmic-import: MElD3RVyO/picture
import vlcsnap2023051621H15M04S666PngDfU4PMeQg from "./images/vlcsnap2023051621H15M04S666Png.png"; // plasmic-import: DfU4pMeQG/picture
import vlcsnap2022091200H37M57S255PngTLYeAmYx from "./images/vlcsnap2022091200H37M57S255Png.png"; // plasmic-import: tLYeAm_yx/picture
import vlcsnap2023040502H20M56S405PngLCEg1C7K from "./images/vlcsnap2023040502H20M56S405Png.png"; // plasmic-import: -lCEg1c7k/picture
import nenStarshineEditionLogoTextpngIyJtPz5C1EYq from "./images/nenStarshineEditionLogoTextpng.png"; // plasmic-import: IYJtPZ5c1EYq/picture
import screenshot33PngLfFGcKgYYiu from "./images/screenshot33Png.png"; // plasmic-import: Lf_fGCKgYYiu/picture
import ugneStillpng0HMl1GxTxKk8 from "./images/ugneStillpng.png"; // plasmic-import: 0hMl1GXTxKk8/picture
import vlcsnap2023110717H50M56S704PngUjDPtU2AQWqb from "./images/vlcsnap2023110717H50M56S704Png.png"; // plasmic-import: ujDPtU2aQWqb/picture
import screenshot37Png7Fz0DkfjpKcW from "./images/screenshot37Png.png"; // plasmic-import: 7fz0DKFJPKcW/picture
import galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: u3z8jgzcZrmHl-/picture
import igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5 from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: YEIKuc4Us-uOc5/picture
import scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: F1Dc1rqcLUfMdJ/picture
import freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: QR2sCt8irZr_xZ/picture
import f2B5KNe2NkQlu4Yi from "./images/f2.jpg"; // plasmic-import: b5kNE2nkQLU4YI/picture
import f3Z1Tdfnxb3V4H5T from "./images/f3.jpg"; // plasmic-import: Z1Tdfnxb3V4h5T/picture
import f4UpCxJZtQkBmwy from "./images/f4.jpg"; // plasmic-import: UpCxJ-ZtQKBmwy/picture
import b1E3AdVKnEdWhdSk from "./images/b1.jpg"; // plasmic-import: e3adVKnEdWhdSK/picture
import b2U3LpTcnWSQ4N from "./images/b2.jpg"; // plasmic-import: u3LpTcnW-sQ4_N/picture
import b3JjuBmEbCNjmCwe from "./images/b3.jpg"; // plasmic-import: jjuBMEbCNjmCwe/picture
import adidasWP3E6VBobZgXt from "./images/adidas.png"; // plasmic-import: wP3e6VBobZg_XT/picture
import hmIbgwVFs1NGuwJb from "./images/hm.png"; // plasmic-import: ibgwVFs1nGuwJB/picture
import kappaB70FlI1Ij5EeDw from "./images/kappa.png"; // plasmic-import: b70FlI1Ij5eeDw/picture
import lacosteQq5M0ROc1FK9Zv from "./images/lacoste.png"; // plasmic-import: QQ5m0rOc1fK9zv/picture
import levisBtwPEu6Om5E0Cj from "./images/levis.png"; // plasmic-import: btwPEu6Om5E0cj/picture

createPlasmicElementProxy;

export const PlasmicTekkouStudios__VariantProps = new Array();

export const PlasmicTekkouStudios__ArgProps = new Array();

const $$ = {};

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicTekkouStudios.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicTekkouStudios.pageMetadata.title}
      />

      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicTekkouStudios.pageMetadata.title}
      />
    </>
  );
}

function PlasmicTekkouStudios__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszNo6Oijq3JlNiY()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__t7Xv4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__xXgNn)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lhl8C)}
                >
                  <Video
                    autoPlay={true}
                    className={classNames(
                      "__wab_instance",
                      sty.htmlVideo___3UeR9
                    )}
                    controls={false}
                    loop={true}
                    muted={true}
                    playsInline={false}
                    poster={vlcsnap2023110717H04M07S779PngJgWZxojzGDue}
                    preload={"auto"}
                    src={
                      "https://drive.google.com/u/1/uc?id=1-KMz_ZZcMZwkg-fLQ-mkgPpzHFBaZLjB&export=download"
                    }
                  />

                  <Video
                    autoPlay={true}
                    className={classNames(
                      "__wab_instance",
                      sty.htmlVideo__vIlxb
                    )}
                    controls={false}
                    loop={true}
                    muted={true}
                    playsInline={false}
                    poster={vlcsnap2023110718H09M08S497PngSWuzSRjSeAjQ}
                    preload={"auto"}
                    src={
                      "https://drive.google.com/u/1/uc?id=1wPWgZ7WEc7nEHMu8ekoI0HqNLSKEKx3I&export=download"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rpyuE
                    )}
                  >
                    {
                      "A new adventure from Tekkou Studios\nMore info coming soon..."
                    }
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cuAH)}
                    displayHeight={"297px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"1075px"}
                    loading={"lazy"}
                    src={{
                      src: tekkouLogoSeptember20234Png2MWgS6QoX0KP,
                      fullWidth: 4587,
                      fullHeight: 1397,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__elNKp
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"OUR GAMES"}
                      </span>
                    </React.Fragment>
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___36FV)}
                    displayHeight={"207px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"1075px"}
                    loading={"lazy"}
                    src={{
                      src: sugarcreekLogoFullpngDBkCf3AHj,
                      fullWidth: 3586,
                      fullHeight: 697,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.columns__tzY9Z)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__j21SY)}
                    >
                      <Embed
                        data-plasmic-name={"embedHtml"}
                        data-plasmic-override={overrides.embedHtml}
                        className={classNames("__wab_instance", sty.embedHtml)}
                        code={
                          '<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/TMQscauzDbA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
                        }
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hNuQy)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xaKVt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: vlcsnap2023052317H36M59S219PngMElD3RVyO,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xb4M)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: vlcsnap2023051621H15M04S666PngDfU4PMeQg,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7M4Yu)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__bn0Ds)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: vlcsnap2022091200H37M57S255PngTLYeAmYx,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qjtbM)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: vlcsnap2023040502H20M56S405PngLCEg1C7K,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__i0UE)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___4M5Yy)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___6BSbX
                        )}
                        component={Link}
                        href={
                          "https://store.steampowered.com/app/2014300/Sugarcreek/"
                        }
                        platform={"gatsby"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#7C7C7C" }}
                          >
                            {"Steam Page"}
                          </span>
                        </React.Fragment>
                      </p.PlasmicLink>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___2EwEj)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__zc9VI
                        )}
                        component={Link}
                        href={
                          "https://www.kickstarter.com/projects/tekkoustudios/sugarcreek-a-2d-story-driven-rpg"
                        }
                        platform={"gatsby"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#4ABE5F" }}
                          >
                            {"Kickstarter"}
                          </span>
                        </React.Fragment>
                      </p.PlasmicLink>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__g0K1)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__oTzTk
                        )}
                        component={Link}
                        href={"https://discord.gg/2WAHRszEUC"}
                        platform={"gatsby"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#3C2D84" }}
                          >
                            {"Discord Server"}
                          </span>
                        </React.Fragment>
                      </p.PlasmicLink>
                    </div>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4ITeC)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__o7MUw)}
                    displayHeight={"365px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"1075px"}
                    loading={"lazy"}
                    src={{
                      src: nenStarshineEditionLogoTextpngIyJtPz5C1EYq,
                      fullWidth: 2221,
                      fullHeight: 744,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__yU7N)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__n2Yyx)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: screenshot33PngLfFGcKgYYiu,
                        fullWidth: 1396,
                        fullHeight: 785,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__u3Ox1)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: ugneStillpng0HMl1GxTxKk8,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0Xhw1)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pYsU)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: vlcsnap2023110717H50M56S704PngUjDPtU2AQWqb,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___5CnK6)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"45%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: screenshot37Png7Fz0DkfjpKcW,
                        fullWidth: 1163,
                        fullHeight: 654,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__kHRnj)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__npk6)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ebz8Z
                        )}
                        component={Link}
                        href={
                          "https://store.steampowered.com/app/1726020/Never_End_Neverland/"
                        }
                        platform={"gatsby"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#7C7C7C" }}
                          >
                            {"Steam Page"}
                          </span>
                        </React.Fragment>
                      </p.PlasmicLink>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__tlaPd)}
                    >
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___7HhXz
                        )}
                        component={Link}
                        href={"https://discord.gg/2WAHRszEUC"}
                        platform={"gatsby"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#3C2D84" }}
                          >
                            {"Discord Server"}
                          </span>
                        </React.Fragment>
                      </p.PlasmicLink>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__deL5X
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"OUR TEAM"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mBXk5
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"Adam Keith - Director"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"Bell (CielDoesArt) - Environment Artist"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"Alex Pulaski - Head Writer"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"CHAOTUNE - Composer"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"Alaina Jeffers - QA Tester & Concept Artist"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 100 }}
                      >
                        {"-"}
                      </span>
                    </React.Fragment>
                  </div>
                </p.Stack>
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox__dWNkL)}>
              <h2
                data-plasmic-name={"h2"}
                data-plasmic-override={overrides.h2}
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2
                )}
              >
                {"Top Collections"}
              </h2>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xKZil)}
            >
              <div className={classNames(projectcss.all, sty.column___5N6A9)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yv1Wb
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ybcCy)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl,
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___7U8Lw
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__kwNrm)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__hlvva
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__slmWr)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5,
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__hUjye
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___9AicD)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fCrj
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xkfzy)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__dHYo
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__sN1Cz)}>
                <ProductCard
                  className={classNames("__wab_instance", sty.productCard__b5I)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hvAdO)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ,
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__o1HWt
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
            </p.Stack>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__fw2UT)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wsToK
                )}
              >
                {"Featured Products"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__awT3T)}
            >
              <div className={classNames(projectcss.all, sty.column__vyNR)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__i9Msd
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yVkSi
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__dyUwF
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a9Gm3
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__dXyRj)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__w1Feb
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p26Iw)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2B5KNe2NkQlu4Yi,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__zRav
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__dPlgn)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___0Eh9X
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__eTiU8)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3Z1Tdfnxb3V4H5T,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___3CIly
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__guPel)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___27TLb
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__kDe1P)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4UpCxJZtQkBmwy,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__kj7Cp
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox___1ZNpg)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ukLu
                )}
              >
                {"Latest Blog"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__luk3)}
            >
              <div className={classNames(projectcss.all, sty.column__hFgfe)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___4WWi)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__keu)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1E3AdVKnEdWhdSk,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__tUne)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__zDdQd)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__azpM8)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2U3LpTcnWSQ4N,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__qaBj0)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__qCbBs)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xr68F)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b3JjuBmEbCNjmCwe,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___9Aeu)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__m6H2H)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidasWP3E6VBobZgXt,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ypYg7)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmIbgwVFs1NGuwJb,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rhUtC)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaB70FlI1Ij5EeDw,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__zdjJl)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteQq5M0ROc1FK9Zv,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ypAak)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levisBtwPEu6Om5E0Cj,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__sbe4D)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "embedHtml", "h2", "featureItem", "footer"],
  header: ["header", "embedHtml", "h2", "featureItem", "footer"],
  embedHtml: ["embedHtml"],
  h2: ["h2"],
  featureItem: ["featureItem"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTekkouStudios__ArgProps,
          internalVariantPropNames: PlasmicTekkouStudios__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTekkouStudios__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTekkouStudios";
  } else {
    func.displayName = `PlasmicTekkouStudios.${nodeName}`;
  }
  return func;
}

export const PlasmicTekkouStudios = Object.assign(
  // Top-level PlasmicTekkouStudios renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    embedHtml: makeNodeComponent("embedHtml"),
    h2: makeNodeComponent("h2"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicTekkouStudios
    internalVariantProps: PlasmicTekkouStudios__VariantProps,
    internalArgProps: PlasmicTekkouStudios__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Tekkou Studios",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTekkouStudios;
/* prettier-ignore-end */
