// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pxrbsjdrcYiKeJrrydSqC9
// Component: _joj0brhT1vpRP
import * as React from "react";
import { Link } from "gatsby";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: DYJN_6hRhobBcR/component
import ProductCard from "../../ProductCard"; // plasmic-import: m9xraW-kpySFIb/component
import Ratings from "../../Ratings"; // plasmic-import: hkLb2r8c9IygmP/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: NbzX9R2oE7Tr_C/component
import BlogPost from "../../BlogPost"; // plasmic-import: d4PABHe6TTTeYg/component
import Footer from "../../Footer"; // plasmic-import: t1MJfdGbdT9xN/component
import MenuButton from "../../MenuButton"; // plasmic-import: tHKra2qqJQ6tmD/component
import { useScreenVariants as useScreenVariantszNo6Oijq3JlNiY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZNo6oijq3JlNiY/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_tekkou_studios.module.css"; // plasmic-import: pxrbsjdrcYiKeJrrydSqC9/projectcss
import * as sty from "./PlasmicFaq.module.css"; // plasmic-import: _joj0brhT1vpRP/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 0VwAWSlI1cyKAc/icon
import DotSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__DotSvgrepoCom1Svg"; // plasmic-import: P3ttIOyDegLRvV/icon
import LocationSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__LocationSvgrepoCom1Svg"; // plasmic-import: sTg6IS6-2Zvsfi/icon
import LogoWhitesvgIcon from "./icons/PlasmicIcon__LogoWhitesvg"; // plasmic-import: U4HHM8rDMXQhVG/icon
import galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: u3z8jgzcZrmHl-/picture
import igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5 from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: YEIKuc4Us-uOc5/picture
import scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: F1Dc1rqcLUfMdJ/picture
import freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: QR2sCt8irZr_xZ/picture
import f2B5KNe2NkQlu4Yi from "./images/f2.jpg"; // plasmic-import: b5kNE2nkQLU4YI/picture
import f3Z1Tdfnxb3V4H5T from "./images/f3.jpg"; // plasmic-import: Z1Tdfnxb3V4h5T/picture
import f4UpCxJZtQkBmwy from "./images/f4.jpg"; // plasmic-import: UpCxJ-ZtQKBmwy/picture
import b1E3AdVKnEdWhdSk from "./images/b1.jpg"; // plasmic-import: e3adVKnEdWhdSK/picture
import b2U3LpTcnWSQ4N from "./images/b2.jpg"; // plasmic-import: u3LpTcnW-sQ4_N/picture
import b3JjuBmEbCNjmCwe from "./images/b3.jpg"; // plasmic-import: jjuBMEbCNjmCwe/picture
import adidasWP3E6VBobZgXt from "./images/adidas.png"; // plasmic-import: wP3e6VBobZg_XT/picture
import hmIbgwVFs1NGuwJb from "./images/hm.png"; // plasmic-import: ibgwVFs1nGuwJB/picture
import kappaB70FlI1Ij5EeDw from "./images/kappa.png"; // plasmic-import: b70FlI1Ij5eeDw/picture
import lacosteQq5M0ROc1FK9Zv from "./images/lacoste.png"; // plasmic-import: QQ5m0rOc1fK9zv/picture
import levisBtwPEu6Om5E0Cj from "./images/levis.png"; // plasmic-import: btwPEu6Om5E0cj/picture
import plant6JpgWypOSqMwkLljC from "./images/plant6Jpg.png"; // plasmic-import: Wyp-oSqMWKLljC/picture
import plant1Jpg4WnEmY0KtT5T from "./images/plant1Jpg.png"; // plasmic-import: 4wnEmY0kt_T5-t/picture
import plant7JpgLppZ16Jixs6SM from "./images/plant7Jpg.png"; // plasmic-import: LppZ16jixs6s_m/picture
import plant5JpgY7RlFovmeoVvz from "./images/plant5Jpg.png"; // plasmic-import: Y7Rl-FovmeoVvz/picture
import plant41JpgDrXI302Mcggq from "./images/plant41Jpg.png"; // plasmic-import: drX__I302mcggq/picture
import plant31JpgY8QgmNoCoGRaU8 from "./images/plant31Jpg.png"; // plasmic-import: Y8qgmNoCoGRaU8/picture
import plant9WebpBuUZlDvLXdwOt from "./images/plant9Webp.webp"; // plasmic-import: BU_UZlDvLXdwOT/picture
import plant2WebpTwez09OFzcfPxW from "./images/plant2Webp.webp"; // plasmic-import: TWEZ09oFzcfPxW/picture
import promowebpVSvYgMiuzEbT from "./images/promowebp.webp"; // plasmic-import: V_SvYGMiuzEbT-/picture

createPlasmicElementProxy;

export const PlasmicFaq__VariantProps = new Array();

export const PlasmicFaq__ArgProps = new Array();

const $$ = {};

export function Head() {
  return <></>;
}

function PlasmicFaq__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszNo6Oijq3JlNiY()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__ti5Pz)}>
            <Header2
              className={classNames("__wab_instance", sty.header2___516D6)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__aX6B)}>
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pvErb)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__hN3Ko
                    )}
                  >
                    {"Behold our FAQ"}
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___4MHx5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x04To
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                        : "All right, friends. Let\u2019s do this. This section will cover basic, frequently asked questions for e-commerce merchants."}
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jZhn)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___0Kwle)}>
                <Header2
                  className={classNames("__wab_instance", sty.header2___5RsQx)}
                />
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox__fPZhh)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__lBIuf
                )}
              >
                {"Top Collections"}
              </h2>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xNnzy)}
            >
              <div className={classNames(projectcss.all, sty.column__cWClA)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wCf9
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p8Arx)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: galinaNMiziNqvJx5MUnsplashjpgU3Z8JgzcZrmHl,
                        fullWidth: 1920,
                        fullHeight: 1278,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__u1KqQ
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__sEbqY)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__jssKx
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iaWuj)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: igorSonFvPxCqgtwcUnsplashjpgYeiKuc4UsUOc5,
                        fullWidth: 640,
                        fullHeight: 481,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__hp9Be
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__bfmfY)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___1SO6
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__diSbf)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: scottWebbORwRlTgBrPoUnsplashjpgF1Dc1RqcLUfMdJ,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings___5TcNl
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__psqVw)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tB3Op
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ah63N)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: freddieMarriageUcfKyTanLuUnsplashjpgQr2SCt8IrZrXZ,
                        fullWidth: 640,
                        fullHeight: 427,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__osfa5
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Product"}
                />
              </div>
            </p.Stack>
            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__x1Hnn)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hlFaZ
                )}
              >
                {"Featured Products"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ekka8)}
            >
              <div className={classNames(projectcss.all, sty.column___81DbY)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__t3Otl
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zwAg7
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__lEuvn
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0YZDu
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__ykRz)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__f6Fqu
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gvr1W)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2B5KNe2NkQlu4Yi,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__kKm1B
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___0B6Mt)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pqbds
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p3SkD)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3Z1Tdfnxb3V4H5T,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__spIlX
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__fl5Ni)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cTqy7
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gSpOt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4UpCxJZtQkBmwy,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__tdoRe
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </p.Stack>
            <div className={classNames(projectcss.all, sty.freeBox__xejj4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yQvvG
                )}
              >
                {"Latest Blog"}
              </div>
            </div>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__yzySm)}
            >
              <div className={classNames(projectcss.all, sty.column__dPzxZ)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__jfVuc)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__glbPk)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1E3AdVKnEdWhdSk,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__bYk7)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__bUhnV)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__t14Kt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2U3LpTcnWSQ4N,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__vyLda)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__jpNCc)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__bkER)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b3JjuBmEbCNjmCwe,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__akpdd)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jb2W9)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidasWP3E6VBobZgXt,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__laYbv)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmIbgwVFs1NGuwJb,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___7XcO5)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaB70FlI1Ij5EeDw,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__tvIGi)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteQq5M0ROc1FK9Zv,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__r0Ufn)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levisBtwPEu6Om5E0Cj,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>
            <Footer
              className={classNames("__wab_instance", sty.footer__ouaB)}
            />
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ntMxk)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__cNi0M
                )}
              >
                {"Big plants"}
              </h2>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__zeDHj)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jCv)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__d51B)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant6JpgWypOSqMwkLljC,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__z4Xdr)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___6GT)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lggmW)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uLqx6
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Donec finibus"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vBvVw
                    )}
                  >
                    {"bigplants"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__n4J4
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__v7Z4J)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dLtSi)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant1Jpg4WnEmY0KtT5T,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__hdUn1)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__foMm5)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__pYibm)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dmK6C
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Nulla suscipit"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__whFmm
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___46P1B
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hRrro)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__urb1D)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant7JpgLppZ16Jixs6SM,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__oQAlm)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__b5Zrc)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6PtF0)}
                >
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hrNh6
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Sed consectetur"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ms4Jd
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__wi9Yq
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Ng82)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant5JpgY7RlFovmeoVvz,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__rQhw)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__s0UCa)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__etoGz)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__bbAFp
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Vestibulum eget"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uDr6Y
                    )}
                  >
                    {"bigplants "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__sDtSy
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___9X4E)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__fhsP2
                )}
              >
                {"Cactuses"}
              </h2>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__je8C2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__aFe93)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pYs9T)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant41JpgDrXI302Mcggq,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___7LcJy)}
                >
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__ehFXs)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xk1Bc)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__m1Yji
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Cras molestie"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fyjDz
                    )}
                  >
                    {"cactuses "}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__yxKu
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__u7Q32)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yifGk)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant31JpgY8QgmNoCoGRaU8,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__iJr)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___7Hbcw)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vkZoV)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___7XQzo
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Curabitur eu tempor"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g1RDw
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__icRhd
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___4C)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hJeyL)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant9WebpBuUZlDvLXdwOt,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__w7ZbF)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__ya23E)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kiHXa)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__an7Rc
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Fusce sagittis"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ndWmg
                    )}
                  >
                    {"Fusce sagittis"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lOp1P
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__kj5Qa)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__doLd8)}
                  displayHeight={"270px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant2WebpTwez09OFzcfPxW,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__wBkJw)}>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg___5Np7I)}
                    role={"img"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wb6LB)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__jthgU
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    {"Integer porta"}
                  </p.PlasmicLink>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c2SlV
                    )}
                  >
                    {"Cactuses"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__oZ92
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <div className={classNames(projectcss.all, sty.freeBox__mJwec)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__aksp)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__n0QDa
                )}
              >
                {"How long does shipping take?"}
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iaCt9
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  : "Now that\u2019s a frequent one all right, ain\u2019t it? Your answer to this should manage customer expectations. Just like a good checkout flow should. Tell them the truth"}
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rVp0M)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pw4Op)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__aa5IA)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__frKxY
                    )}
                  >
                    {"US shipping will take between 3 to 5 business days."}
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___82Eqv)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__yWeU)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vp9H8
                    )}
                  >
                    {
                      "International shipping will take between 5 and 10 business days."
                    }
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__g1X0C)}
                >
                  <DotSvgrepoCom1SvgIcon
                    className={classNames(projectcss.all, sty.svg__bgC1F)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bichT
                    )}
                  >
                    {
                      "Mars shipping will be automatically redirected to Elon Musk\u2019s Twitter account."
                    }
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wdw4G)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4___1XbRx
                )}
              >
                {"How do refunds and returns work?"}
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tfi3B
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  : "It happens. Even the most beautiful of plants will disappoint someone. Again, tell it like it is:"}
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__osRhs)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___9EBeh)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__tOeKp)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__eaEdu)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__euUnu
                      )}
                    >
                      {"All discounted items sales are final."}
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___48Rnr)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg___1DlI)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z7IUx
                      )}
                    >
                      {
                        "If you\u2019d like another version of your item, please use the return label. Instructions are printed on its back."
                      }
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hF2O6)}
                  >
                    <DotSvgrepoCom1SvgIcon
                      className={classNames(projectcss.all, sty.svg__gDwz8)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dPuzH
                      )}
                    >
                      {
                        "If your item is damaged or not functioning correctly, email us at info@planty.com, and we\u2019ll refund you + send you a new one ASAP!"
                      }
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__c0MOa)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__wcau4
                )}
              >
                {"Rapid-fire questions"}
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wzk0Z
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  : "GDPR, am I right? Make sure you\u2019re as transparent as possible with your data handling process. Or, if you\u2019re using Snipcart, just refer to our ToS and DPA"}
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___3YBye)}
            >
              <h4
                className={classNames(
                  projectcss.all,
                  projectcss.h4,
                  projectcss.__wab_text,
                  sty.h4__rosxx
                )}
              >
                {"How do you handle sensitive customer information?"}
              </h4>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ez0Ne
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  : "GDPR, am I right? Make sure you\u2019re as transparent as possible with your data handling process. Or, if you\u2019re using Snipcart, just refer to our ToS and DPA"}
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zrZd)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__awVlt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__npgCs
                    )}
                  >
                    {"Q: Why is this Planty theme so beautiful?"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c0Il7
                    )}
                  >
                    {"A: We hired our first designer a couple of months ago."}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___25Aw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bOuW6
                    )}
                  >
                    {"Q: Why did you build a theme for Stackbit?"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yN69T
                    )}
                  >
                    {
                      "A: We believe in Stackbit\u2019s promise of opening up the JAMstack to more developers. Plus, we trust these folks.\n Read more about Stackbit"
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2RlpT)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1YYGv
                    )}
                  >
                    {"Q: How many people work at Snipcart? "}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ar26V
                    )}
                  >
                    {
                      "A: Not a lot! We\u2019re a small, bootstrapped team of eight human beings. Michael might be a robot, though. "
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__avuDl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4Vfy7
                    )}
                  >
                    {"Q: Why is Snipcart based in Qu\u00e9bec City?"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lGnPx
                    )}
                  >
                    {"A: Have you been here? It\u2019s beaaautiful!"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qbfQt)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oYzt4
                    )}
                  >
                    {"Q: What\u2019s the meaning of life? "}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Z8Vq
                    )}
                  >
                    {
                      "A: We\u2019re not quite sure. But building useful products with people we love feels meaningful enough."
                    }
                  </div>
                </div>
              </p.Stack>
            </p.Stack>
          </div>
          <Footer className={classNames("__wab_instance", sty.footer__ezdP4)} />
          <div className={classNames(projectcss.all, sty.freeBox__vpVCk)}>
            <div className={classNames(projectcss.all, sty.freeBox__lOeV6)}>
              <div className={classNames(projectcss.all, sty.columns___3Rnx7)}>
                <div className={classNames(projectcss.all, sty.column__vjHl2)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__sxrgY)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "562px"
                        : "562px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "947px"
                        : "947px"
                    }
                    loading={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "lazy"
                        : "lazy"
                    }
                    src={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            src: promowebpVSvYgMiuzEbT,
                            fullWidth: 720,
                            fullHeight: 525,
                            aspectRatio: undefined
                          }
                        : {
                            src: promowebpVSvYgMiuzEbT,
                            fullWidth: 720,
                            fullHeight: 525,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__mnr2X)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__di81I
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Behold our FAQ"
                      : "Still have questions?\nContact us. "}
                  </h1>
                  <div
                    className={classNames(projectcss.all, sty.columns__c2PXt)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__tg68Q)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__riSfI
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Behold our FAQ"
                          : "226 rue St-Joseph E, \nQu\u00e9bec, QC, Canada, \nG1K 3A9"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__llCmv
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Behold our FAQ"
                          : "+1-202-555-0112"}
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__lvR5T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zr14J
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Behold our FAQ"
                          : "geeks@snipcart.com"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__c8SHl
                        )}
                      >
                        <p.Stack
                          as={p.PlasmicLink}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__oBvSz
                          )}
                          component={Link}
                          platform={"gatsby"}
                        >
                          <LocationSvgrepoCom1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__y6Yye
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uq4Ns
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobile")
                              ? "Discover"
                              : "On the map"}
                          </div>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </div>
                </p.Stack>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xAnPz)}>
              <div className={classNames(projectcss.all, sty.freeBox__kt3Pt)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tIuAk)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xkcUl)}
                  >
                    <MenuButton
                      data-plasmic-name={"menuButton"}
                      data-plasmic-override={overrides.menuButton}
                      className={classNames("__wab_instance", sty.menuButton)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ek8Kk)}
                    >
                      <p.PlasmicIcon
                        PlasmicIconType={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? LogoWhitesvgIcon
                            : LogoWhitesvgIcon
                        }
                        className={classNames(projectcss.all, sty.svg__gh8K5)}
                        role={"img"}
                      />

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__qZjNr
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/store`
                        }
                        platform={"gatsby"}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Store"
                          : "Store"}
                      </p.PlasmicLink>
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__rMsKh
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/about`
                        }
                        platform={"gatsby"}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "About"
                          : "About"}
                      </p.PlasmicLink>
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__mpZBy
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "#"
                            : `/faq`
                        }
                        platform={"gatsby"}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Faq"
                          : "Faq"}
                      </p.PlasmicLink>
                    </p.Stack>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__m8XV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vUoVm
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "\u00a9 Company. All rights reserved. This site proudly built with "
                          : "\u00a9 Company. All rights reserved. This site proudly built with "}
                      </div>
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___8Se31
                        )}
                        component={Link}
                        href={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "https://www.plasmic.app/"
                            : "https://www.plasmic.app/"
                        }
                        platform={"gatsby"}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "Plasmic"
                          : "Plasmic"}
                      </p.PlasmicLink>
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "header",
    "featureItem",
    "bigPlants",
    "cactuses",
    "menuButton"
  ],

  foreground2: ["foreground2"],
  header: ["header", "featureItem"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  menuButton: ["menuButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFaq__ArgProps,
          internalVariantPropNames: PlasmicFaq__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFaq__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaq";
  } else {
    func.displayName = `PlasmicFaq.${nodeName}`;
  }
  return func;
}

export const PlasmicFaq = Object.assign(
  // Top-level PlasmicFaq renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    header: makeNodeComponent("header"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    menuButton: makeNodeComponent("menuButton"),
    // Metadata about props expected for PlasmicFaq
    internalVariantProps: PlasmicFaq__VariantProps,
    internalArgProps: PlasmicFaq__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFaq;
/* prettier-ignore-end */
